# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 313)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 40, 591, 31))
        self.textEdit.setObjectName("textEdit")
        self.btn_copy = QtWidgets.QPushButton(self.centralwidget)
        self.btn_copy.setGeometry(QtCore.QRect(620, 40, 75, 31))
        self.btn_copy.setObjectName("copy")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 120, 591, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.btn_insert = QtWidgets.QPushButton(self.centralwidget)
        self.btn_insert.setGeometry(QtCore.QRect(620, 120, 75, 31))
        self.btn_insert.setObjectName("insert")
        self.btn_launch = QtWidgets.QPushButton(self.centralwidget)
        self.btn_launch.setGeometry(QtCore.QRect(290, 230, 111, 41))
        self.btn_launch.setObjectName("launch")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(False)
        self.progressBar.setGeometry(QtCore.QRect(180, 190, 471, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.choose = QtWidgets.QComboBox(self.centralwidget)
        self.choose.setGeometry(QtCore.QRect(20, 190, 141, 22))
        self.choose.setObjectName("choose")
        self.choose.addItem("")
        self.choose.addItem("")
        self.choose.addItem("")
        self.choose.addItem("")
        self.choose.addItem("")
        self.choose.addItem("")
        self.choose.addItem("")
        self.choose.addItem("")
        self.choose.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 181, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 181, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 141, 16))
        self.label_3.setObjectName("label_3")
        # MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Transferring Files"))
        self.btn_copy.setText(_translate("MainWindow", "TRANSFER"))
        self.btn_insert.setText(_translate("MainWindow", "INSERT"))
        self.btn_launch.setText(_translate("MainWindow", "LAUNCH"))
        self.choose.setItemText(0, _translate("MainWindow", "..."))
        self.choose.setItemText(1, _translate("MainWindow", "Torrent"))
        self.choose.setItemText(2, _translate("MainWindow", "Video"))
        self.choose.setItemText(3, _translate("MainWindow", "Music"))
        self.choose.setItemText(4, _translate("MainWindow", "Document Word"))
        self.choose.setItemText(5, _translate("MainWindow", "Document Notebook"))
        self.choose.setItemText(6, _translate("MainWindow", "Install File"))
        self.choose.setItemText(7, _translate("MainWindow", "Document HTML"))
        self.choose.setItemText(8, _translate("MainWindow", "Archive(RAR)"))
        self.label.setText(_translate("MainWindow", "Откуда будут переносится файлы"))
        self.label_2.setText(_translate("MainWindow", "Куда будут переносится файлы"))
        self.label_3.setText(_translate("MainWindow", "Выбрать нужные файлы"))
